name: Publish LibOSI debian package

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  create_release:
    runs-on: ubuntu-latest
    outputs:
      v-version: ${{ steps.version.outputs.v-version }}

    steps:
      - name: Get next version
        uses: reecetech/version-increment@2023.10.2
        id: version
        with:
          release_branch: master
          use_api: true

  build_and_publish:
    needs: create_release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, ubuntu-24.04]

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get -qq update -y
          sudo apt-get -qq install cmake ninja-build rapidjson-dev libgtest-dev libglib2.0-dev -y

      - name: Check out
        uses: actions/checkout@v4

      - name: Build package
        run: | 
          cmake -B build -GNinja -DCMAKE_INSTALL_PREFIX=/usr -DVERSION=${{ needs.create_release.outputs.v-version }}
          ninja -C build
          ninja -C build package

      - name: Upload debian package to release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.create_release.outputs.v-version }}
          files: |
            build/*.deb
