name: Test LibOSI library

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  test_libosi:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, ubuntu-24.04]

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get -qq update -y
          sudo apt-get -qq install cmake ninja-build rapidjson-dev libgtest-dev libglib2.0-dev -y

      - name: Check out
        uses: actions/checkout@v4

      - name: Build with testing enabled and run tests
        working-directory: .
        run: | 
          cmake -B build -GNinja -DENABLE_TESTING=ON
          ninja -C build
          ninja -C build test
