name: Test LibOSI library

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

# Automatically cancel any previous workflow on new push.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  test_libosi:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get -qq update -y
          sudo apt-get -qq install cmake ninja-build rapidjson-dev libgtest-dev libglib2.0-dev -y

      - name: Check out
        uses: actions/checkout@v4

      - name: Build with testing enabled and run tests
        run: | 
          cmake -B build -GNinja -DENABLE_TESTING=ON
          ninja -C build -j$(nproc)
          ninja -C build test

      - name: Test installing Debian package
        run: |
          ninja -C build package
          sudo dpkg -i build/libosi*.deb
          if ! ldconfig -p | grep -q libosi; then
            echo "libosi not found in linker cache Debian Package corrupt!"
            exit 1
          fi
  